// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdysW51ITEethl81mK5ZY__G4926MZHTY',
    appId: '1:486760118149:web:82ef8865417360de5436ec',
    messagingSenderId: '486760118149',
    projectId: 'shoppingapptask-52ae6',
    authDomain: 'shoppingapptask-52ae6.firebaseapp.com',
    storageBucket: 'shoppingapptask-52ae6.appspot.com',
    measurementId: 'G-1FG26PYXCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC68BHaZEpOxz4lKiWuEC8grNlllBdmLtw',
    appId: '1:486760118149:android:b933dd44ac34ef8f5436ec',
    messagingSenderId: '486760118149',
    projectId: 'shoppingapptask-52ae6',
    storageBucket: 'shoppingapptask-52ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCbILl6LF5eGd2UMPEDpJWJ8BdurkBC48',
    appId: '1:486760118149:ios:cbdbb2cc37191c685436ec',
    messagingSenderId: '486760118149',
    projectId: 'shoppingapptask-52ae6',
    storageBucket: 'shoppingapptask-52ae6.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseShoppingAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCbILl6LF5eGd2UMPEDpJWJ8BdurkBC48',
    appId: '1:486760118149:ios:cbdbb2cc37191c685436ec',
    messagingSenderId: '486760118149',
    projectId: 'shoppingapptask-52ae6',
    storageBucket: 'shoppingapptask-52ae6.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseShoppingAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdysW51ITEethl81mK5ZY__G4926MZHTY',
    appId: '1:486760118149:web:5647152eb1a7937f5436ec',
    messagingSenderId: '486760118149',
    projectId: 'shoppingapptask-52ae6',
    authDomain: 'shoppingapptask-52ae6.firebaseapp.com',
    storageBucket: 'shoppingapptask-52ae6.appspot.com',
    measurementId: 'G-7RE799TCW6',
  );
}
